/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.operations.ObjectFinder;
import controller.operations.userOperations.CustomerOperations;
import javax.swing.table.DefaultTableModel;
import model.RequestType;
import model.factories.WoodenBookshelfFactory;
import model.factories.WoodenTableFactory;
import model.factories.WoodenWardrobeFactory;
import model.product.WoodenBookshelf;
import model.product.WoodenTable;
import model.product.WoodenWardrobe;
import model.users.Customer;

/**
 *
 * @author Ege
 */
public class BuyProductFrame extends javax.swing.JFrame {
    Customer customer;
    int customerId;

    /**
     * Creates new form BuyProductFrame
     */
    public BuyProductFrame(int customerId) {
        this.customerId=customerId;
        this.customer=ObjectFinder.findCustomerFromCustomerId(this.customerId);
        initComponents();
        setIcon();
        
        clearAllBuyMessage();
        customerMoneyLabel.setText("");
        messageGeneral.setText("");
        
        
        fillMoneyLabel();
        fillPreviousBuyRequestTable();
    }
    private void setIcon(){
        backToCustomerFrame.setIcon(new javax.swing.ImageIcon("arrow-112-48.png"));
        jLabel1.setIcon(new javax.swing.ImageIcon("table-256.png")); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon("wardrobe-256.png")); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon("books-256.png")); // NOI18N
        
        
    }
    void clearAllBuyMessage(){
        messageGeneral.setText("");
        
        
    }
    private void fillMoneyLabel(){
        String money=String.valueOf(customer.getMoney());
        customerMoneyLabel.setText(money+"$"); 
    }
    private void fillPreviousBuyRequestTable(){
        
        DefaultTableModel model=(DefaultTableModel) previousBuyRequestTable.getModel();
       for(int i=0;i<customer.getRequests().size();i++){
           if(!customer.getRequests().get(i).getRequestType().equals(RequestType.WishMoneyFromFamily)){
               if(customer.getRequests().get(i).getRequestType().equals(RequestType.WoodTable)){
                   Object[] products={String.valueOf((int)customer.getRequests().get(i).getAmount()),(int)customer.getRequests().get(i).getAmount()*(int)new WoodenTableFactory().getSalePrice(),String.valueOf(customer.getRequests().get(i).getRequestType())
         ,String.valueOf(customer.getRequests().get(i).getStatus())}; 
         model.addRow(products);
               }
               else if(customer.getRequests().get(i).getRequestType().equals(RequestType.WoodBookshelf)){
                   Object[] products={String.valueOf((int)customer.getRequests().get(i).getAmount()),(int)customer.getRequests().get(i).getAmount()*(int)new WoodenBookshelfFactory().getSalePrice(),String.valueOf(customer.getRequests().get(i).getRequestType())
         ,String.valueOf(customer.getRequests().get(i).getStatus())}; 
         model.addRow(products);
               }else{
                   Object[] products={String.valueOf((int)customer.getRequests().get(i).getAmount()),(int)customer.getRequests().get(i).getAmount()*(int)new WoodenWardrobeFactory().getSalePrice(),String.valueOf(customer.getRequests().get(i).getRequestType())
         ,String.valueOf(customer.getRequests().get(i).getStatus())}; 
         model.addRow(products);
                   
               }
               
           }
          
         
       }
        
    }
     private void removeRows(){
        DefaultTableModel model=(DefaultTableModel) previousBuyRequestTable.getModel();
        int row=0;
        while(model.getRowCount()>0){
            model.removeRow(row);
        } 
    }
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        customerMoneyLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        buyTableAmountField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        buyWardrobeAmountField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        buyBookshelfAmountField = new javax.swing.JTextField();
        buyTableButton = new javax.swing.JButton();
        buyWardrobeButton = new javax.swing.JButton();
        buyBookshelfButton = new javax.swing.JButton();
        messageGeneral = new javax.swing.JLabel();
        backToCustomerFrame = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        previousBuyRequestTable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ege\\Downloads\\table-256.png")); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ege\\Downloads\\wardrobe-256.png")); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ege\\Downloads\\books-256.png")); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Your Budget:");

        customerMoneyLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        customerMoneyLabel.setText("Money");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Buy Table Amount:");

        buyTableAmountField.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        buyTableAmountField.setText("Min Amount:100");
        buyTableAmountField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buyTableAmountFieldMouseClicked(evt);
            }
        });
        buyTableAmountField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyTableAmountFieldActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Buy Wardrobe Amount:");

        buyWardrobeAmountField.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        buyWardrobeAmountField.setText("Min Amount:100");
        buyWardrobeAmountField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buyWardrobeAmountFieldMouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Buy Bookshelf Amount:");

        buyBookshelfAmountField.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        buyBookshelfAmountField.setText("Min Amount:100");
        buyBookshelfAmountField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buyBookshelfAmountFieldMouseClicked(evt);
            }
        });

        buyTableButton.setBackground(new java.awt.Color(0, 230, 64));
        buyTableButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buyTableButton.setText("Buy Table");
        buyTableButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyTableButtonActionPerformed(evt);
            }
        });

        buyWardrobeButton.setBackground(new java.awt.Color(0, 230, 64));
        buyWardrobeButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buyWardrobeButton.setText("Buy Wardrobe");
        buyWardrobeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyWardrobeButtonActionPerformed(evt);
            }
        });

        buyBookshelfButton.setBackground(new java.awt.Color(0, 230, 64));
        buyBookshelfButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buyBookshelfButton.setText("Buy Bookshelf");
        buyBookshelfButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyBookshelfButtonActionPerformed(evt);
            }
        });

        messageGeneral.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        messageGeneral.setText("jLabel8");

        backToCustomerFrame.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ege\\Documents\\NetBeansProjects\\FinalProject\\arrow-112-48.png")); // NOI18N
        backToCustomerFrame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToCustomerFrameActionPerformed(evt);
            }
        });

        previousBuyRequestTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Amount", "Price($)", "Product Type", "Request Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(previousBuyRequestTable);
        if (previousBuyRequestTable.getColumnModel().getColumnCount() > 0) {
            previousBuyRequestTable.getColumnModel().getColumn(0).setResizable(false);
            previousBuyRequestTable.getColumnModel().getColumn(1).setResizable(false);
            previousBuyRequestTable.getColumnModel().getColumn(2).setResizable(false);
        }

        jPanel1.setBackground(new java.awt.Color(250, 190, 88));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Previous Buy Request");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Unit Price:150$");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Unit Price:750$");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Unit Price:370$");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(buyTableButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(197, 197, 197)
                .addComponent(buyWardrobeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buyBookshelfButton, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(backToCustomerFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(customerMoneyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(messageGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(buyTableAmountField, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(45, 45, 45)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buyWardrobeAmountField, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buyBookshelfAmountField, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(45, 45, 45))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 965, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(383, 383, 383)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(97, 97, 97)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(83, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(203, 203, 203)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(138, 138, 138))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(customerMoneyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(backToCustomerFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(58, 58, 58)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buyTableAmountField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buyWardrobeAmountField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buyBookshelfAmountField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buyTableButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buyWardrobeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buyBookshelfButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(messageGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buyTableButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyTableButtonActionPerformed
        if(buyTableAmountField.getText().equals("")){
            messageGeneral.setText("Amount can not be empty please enter table amount");
        }else{
            if(Integer.parseInt(buyTableAmountField.getText())>=100){
                int tableAmount=Integer.parseInt(buyTableAmountField.getText());
            String message=CustomerOperations.buyWoodTable(customer, tableAmount);
            this.customer=ObjectFinder.findCustomerFromCustomerId(customer.getUserId());
            fillMoneyLabel();
            messageGeneral.setText(message);
            removeRows();
            fillPreviousBuyRequestTable();
            }else{
                messageGeneral.setText("You can not buy table less than 100");
            }
            
        }
    }//GEN-LAST:event_buyTableButtonActionPerformed

    private void backToCustomerFrameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToCustomerFrameActionPerformed
        //Customer customerr=ObjectFinder.findCustomerFromCustomerId(customer.getUserId());
        //this.customer=customerr;
        CustomerFrame customerFrame=new CustomerFrame(customer.getUserId());
        this.setVisible(false);
        customerFrame.setVisible(true);
    }//GEN-LAST:event_backToCustomerFrameActionPerformed

    private void buyTableAmountFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buyTableAmountFieldMouseClicked
        clearAllBuyMessage();
        buyTableAmountField.setText("");
    }//GEN-LAST:event_buyTableAmountFieldMouseClicked

    private void buyTableAmountFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyTableAmountFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buyTableAmountFieldActionPerformed

    private void buyWardrobeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyWardrobeButtonActionPerformed
        if(buyWardrobeAmountField.getText().equals("")){
            messageGeneral.setText("Amount can not be empty please enter wardrobe amount"); 
        }else{
            if(Integer.parseInt(buyWardrobeAmountField.getText())>=100){
              int tableAmount=Integer.parseInt(buyWardrobeAmountField.getText());
            String message=CustomerOperations.buyWoodWardrobe(customer, tableAmount);
            this.customer=ObjectFinder.findCustomerFromCustomerId(customer.getUserId());
            fillMoneyLabel();
            messageGeneral.setText(message);
            removeRows();
            fillPreviousBuyRequestTable();  
            }else{
                messageGeneral.setText("You can not buy wardrobe less than 100");
            }
            
            
        }
    }//GEN-LAST:event_buyWardrobeButtonActionPerformed

    private void buyWardrobeAmountFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buyWardrobeAmountFieldMouseClicked
        clearAllBuyMessage();
        buyWardrobeAmountField.setText("");
    }//GEN-LAST:event_buyWardrobeAmountFieldMouseClicked

    private void buyBookshelfAmountFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buyBookshelfAmountFieldMouseClicked
       clearAllBuyMessage();
       buyBookshelfAmountField.setText("");
    }//GEN-LAST:event_buyBookshelfAmountFieldMouseClicked

    private void buyBookshelfButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyBookshelfButtonActionPerformed
         if(buyBookshelfAmountField.getText().equals("")){
            messageGeneral.setText("Amount can not be empty please enter bookshelf amount"); 
        }else{
             
            if(Integer.parseInt(buyBookshelfAmountField.getText())>=100){
               int tableAmount=Integer.parseInt(buyBookshelfAmountField.getText());
            String message=CustomerOperations.buyWoodBookshelf(customer, tableAmount);
            this.customer=ObjectFinder.findCustomerFromCustomerId(customer.getUserId());
            fillMoneyLabel();
            messageGeneral.setText(message);
            removeRows();
            fillPreviousBuyRequestTable(); 
            }else{
                messageGeneral.setText("You can not buy bookshelf less than 100");
            }
            
            
        }
    }//GEN-LAST:event_buyBookshelfButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backToCustomerFrame;
    private javax.swing.JTextField buyBookshelfAmountField;
    private javax.swing.JButton buyBookshelfButton;
    private javax.swing.JTextField buyTableAmountField;
    private javax.swing.JButton buyTableButton;
    private javax.swing.JTextField buyWardrobeAmountField;
    private javax.swing.JButton buyWardrobeButton;
    private javax.swing.JLabel customerMoneyLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel messageGeneral;
    private javax.swing.JTable previousBuyRequestTable;
    // End of variables declaration//GEN-END:variables
}
