/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.operations.ObjectFinder;
import javax.swing.table.DefaultTableModel;
import model.users.Customer;

/**
 *
 * @author Ege
 */
public class CustomerFrame extends javax.swing.JFrame {
    Customer customer;
    int customerId;

    /**
     * Creates new form CustomerFrame
     */
    public CustomerFrame(int customerId) {
        this.customerId=customerId;
        this.customer=ObjectFinder.findCustomerFromCustomerId(this.customerId);
        
        
        initComponents();
        fillNotificationTable();
        setIcon();
        
        customerNameLabel.setText("");
        moneyLabel.setText("");
        numberOfTotalProduct.setText("");
        numberOfRequests.setText("");
        FillCustomerInformation();
    }
    private void setIcon(){
         buyProductOrWishMoneyButton.setIcon(new javax.swing.ImageIcon("buy-2-24.png")); // NOI18N
         sellProductButton.setIcon(new javax.swing.ImageIcon("banknotes-24.png")); // NOI18N
         gamblingButton.setIcon(new javax.swing.ImageIcon("dice-24.png"));
         wishMoneyFromFamilyButton.setIcon(new javax.swing.ImageIcon("pray (1).png")); 
        
    
    }
    
private void FillCustomerInformation(){
        int numberOfProduct=0;
        customerNameLabel.setText(customer.getUserName());
        String money=String.valueOf(customer.getMoney());
        String dolarSembol="$";
        moneyLabel.setText(money.concat(dolarSembol));
        for(int i=0;i<customer.getProducts().size();i++){
            numberOfProduct+=customer.getProducts().get(i).getNumberOfProduct();
        }
        numberOfTotalProduct.setText(String.valueOf(numberOfProduct));
        String numberOfRequest=String.valueOf(customer.getRequests().size());
        numberOfRequests.setText(numberOfRequest);
        
               
        
    }
private void fillNotificationTable(){
    DefaultTableModel model=(DefaultTableModel) notificationsTable.getModel();
    if(customer.getNotifications().size()==0){
        String message="There is no notification...";
        Object[] notification={message};
        model.addRow(notification); 
    }else{
        for(String s:customer.getNotifications()){
            Object[] notification={s};
            model.addRow(notification);
        }
    }
    
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        buyProductOrWishMoneyButton = new javax.swing.JButton();
        sellProductButton = new javax.swing.JButton();
        gamblingButton = new javax.swing.JButton();
        wishMoneyFromFamilyButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        notificationsTable = new javax.swing.JTable();
        clearButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        customerNameLabel = new javax.swing.JLabel();
        moneyLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        numberOfTotalProduct = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        numberOfRequests = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(41, 241, 195));

        buyProductOrWishMoneyButton.setBackground(new java.awt.Color(108, 122, 137));
        buyProductOrWishMoneyButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        buyProductOrWishMoneyButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ege\\Downloads\\buy-2-24.png")); // NOI18N
        buyProductOrWishMoneyButton.setText("Buy Product");
        buyProductOrWishMoneyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyProductOrWishMoneyButtonActionPerformed(evt);
            }
        });

        sellProductButton.setBackground(new java.awt.Color(108, 127, 132));
        sellProductButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        sellProductButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ege\\Downloads\\banknotes-24.png")); // NOI18N
        sellProductButton.setText("Sell Product");
        sellProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sellProductButtonActionPerformed(evt);
            }
        });

        gamblingButton.setBackground(new java.awt.Color(108, 127, 132));
        gamblingButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        gamblingButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ege\\Downloads\\dice-24.png")); // NOI18N
        gamblingButton.setText("Gambling");
        gamblingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gamblingButtonActionPerformed(evt);
            }
        });

        wishMoneyFromFamilyButton.setBackground(new java.awt.Color(108, 127, 132));
        wishMoneyFromFamilyButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        wishMoneyFromFamilyButton.setText("Wish Money From Family");
        wishMoneyFromFamilyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wishMoneyFromFamilyButtonActionPerformed(evt);
            }
        });

        notificationsTable.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        notificationsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Notifications"
            }
        ));
        jScrollPane1.setViewportView(notificationsTable);
        if (notificationsTable.getColumnModel().getColumnCount() > 0) {
            notificationsTable.getColumnModel().getColumn(0).setResizable(false);
        }

        clearButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        clearButton.setText("Clear Notifications");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ege\\Documents\\NetBeansProjects\\FinalProject\\logout-32.png")); // NOI18N
        jButton2.setText("Logout");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(gamblingButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buyProductOrWishMoneyButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sellProductButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(wishMoneyFromFamilyButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(409, 409, 409)
                        .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(wishMoneyFromFamilyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(buyProductOrWishMoneyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(sellProductButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(gamblingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clearButton, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                .addGap(5, 5, 5))
        );

        jPanel2.setBackground(new java.awt.Color(242, 120, 75));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Name");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Money");

        customerNameLabel.setText("jLabel3");

        moneyLabel.setText("jLabel3");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Number of Products");

        numberOfTotalProduct.setText("jLabel4");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Number of Request");

        numberOfRequests.setText("jLabel5");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customerNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(moneyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(numberOfTotalProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numberOfRequests, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customerNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(moneyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numberOfTotalProduct)
                    .addComponent(numberOfRequests))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gamblingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gamblingButtonActionPerformed
        this.setVisible(false);
        GamblingFrame gamblingFrame=new GamblingFrame(customer.getUserId());
        gamblingFrame.setVisible(true);
    }//GEN-LAST:event_gamblingButtonActionPerformed

    private void sellProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sellProductButtonActionPerformed
        SellProductFrame sellProductFrame=new SellProductFrame(customer.getUserId());
        this.setVisible(false);
        sellProductFrame.setVisible(true);
    }//GEN-LAST:event_sellProductButtonActionPerformed

    private void wishMoneyFromFamilyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wishMoneyFromFamilyButtonActionPerformed
       WishMoneyFromFamilyFrame wishMoneyFromFamilyFrame=new WishMoneyFromFamilyFrame(customer.getUserId());
       this.setVisible(false);
       wishMoneyFromFamilyFrame.setVisible(true);
    }//GEN-LAST:event_wishMoneyFromFamilyButtonActionPerformed

    private void buyProductOrWishMoneyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyProductOrWishMoneyButtonActionPerformed
        BuyProductFrame buyProductFrame=new BuyProductFrame(customer.getUserId());
        this.setVisible(false);
        buyProductFrame.setVisible(true);
    }//GEN-LAST:event_buyProductOrWishMoneyButtonActionPerformed
  private void removeRows(){
        DefaultTableModel model=(DefaultTableModel) notificationsTable.getModel();
        int row=0;
        while(model.getRowCount()>0){
            model.removeRow(row);
        } 
    }
    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        removeRows();
        customer.clearNotification();
        fillNotificationTable();
        
    }//GEN-LAST:event_clearButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       this.setVisible(false);
       LoginFrame loginFrame=new LoginFrame();
       loginFrame.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buyProductOrWishMoneyButton;
    private javax.swing.JButton clearButton;
    private javax.swing.JLabel customerNameLabel;
    private javax.swing.JButton gamblingButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel moneyLabel;
    private javax.swing.JTable notificationsTable;
    private javax.swing.JLabel numberOfRequests;
    private javax.swing.JLabel numberOfTotalProduct;
    private javax.swing.JButton sellProductButton;
    private javax.swing.JButton wishMoneyFromFamilyButton;
    // End of variables declaration//GEN-END:variables
}
