/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.operations.ObjectFinder;
import controller.operations.userOperations.CustomerOperations;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.users.Customer;

/**
 *
 * @author Ege
 */
public class GamblingFrame extends javax.swing.JFrame {
    int selectedDice=-1;
    int customerId;
    Customer customer;

    /**
     * Creates new form GamlingFrame
     */
    public GamblingFrame(int customerId) {
        this.customerId=customerId;
        this.customer=ObjectFinder.findCustomerFromCustomerId(customerId);
        initComponents();
        messageLabel.setText("");
        moneyLabel.setText("");
        resultLabel.setVisible(false);
        fillMoneyInformation();
   
    }
    private void fillMoneyInformation(){
        this.customer=ObjectFinder.findCustomerFromCustomerId(customerId);
        moneyLabel.setText(String.valueOf((int)customer.getMoney())+"$");
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dice1Label = new javax.swing.JLabel();
        rollDiceButton = new javax.swing.JButton();
        dice2Label = new javax.swing.JLabel();
        dice3Label = new javax.swing.JLabel();
        dice4Label = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        messageLabel = new javax.swing.JLabel();
        resultLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        moneyLabel = new javax.swing.JLabel();
        betField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        dice1Label.setIcon(new javax.swing.ImageIcon("dice-1-1-128.png")); // NOI18N
        dice1Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dice1LabelMouseClicked(evt);
            }
        });

        rollDiceButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rollDiceButton.setIcon(new javax.swing.ImageIcon("dice-24.png")); // NOI18N
        rollDiceButton.setText("Roll Dice");
        rollDiceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rollDiceButtonActionPerformed(evt);
            }
        });

        dice2Label.setIcon(new javax.swing.ImageIcon("dice-2-2-128.png")); // NOI18N
        dice2Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dice2LabelMouseClicked(evt);
            }
        });

        dice3Label.setIcon(new javax.swing.ImageIcon("dice-3-1-128.png")); // NOI18N
        dice3Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dice3LabelMouseClicked(evt);
            }
        });

        dice4Label.setIcon(new javax.swing.ImageIcon("dice-4-1-128.png")); // NOI18N
        dice4Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dice4LabelMouseClicked(evt);
            }
        });

        backButton.setIcon(new javax.swing.ImageIcon("arrow-112-48.png")); // NOI18N
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        messageLabel.setText("message");

        resultLabel.setText("resultDice");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Money");

        moneyLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        moneyLabel.setText("10000");

        betField.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        betField.setText("Min Bet:1000$");
        betField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                betFieldMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(101, 101, 101)
                                .addComponent(dice1Label)
                                .addGap(18, 18, 18)
                                .addComponent(dice2Label)
                                .addGap(29, 29, 29)
                                .addComponent(dice3Label)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(dice4Label))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                                    .addComponent(moneyLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(305, 305, 305)
                        .addComponent(resultLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(rollDiceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(betField, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(messageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(moneyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dice2Label)
                    .addComponent(dice1Label)
                    .addComponent(dice3Label)
                    .addComponent(dice4Label))
                .addGap(36, 36, 36)
                .addComponent(resultLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(betField, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(rollDiceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(messageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rollDiceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rollDiceButtonActionPerformed
        if(selectedDice==-1){
            messageLabel.setText("Please select dice to play game");
            
        }
        else{
            if(betField.getText().equals("")||betField.getText().equals("Min Bet:1000$")){
                messageLabel.setText("Please enter bet amount to roll dice!");
            }
            else{
                if(Integer.parseInt(betField.getText())>=1000){
                    if((int)customer.getMoney()<Integer.parseInt(betField.getText())){
                    messageLabel.setText("You don't have enough money to roll dice");
                }else{
                    int result=CustomerOperations.gamble(customer, Double.parseDouble(betField.getText()),selectedDice);
                    if(result==0){
                        showResult(selectedDice);
                        double earnedMoney=(Integer.parseInt(betField.getText())+Integer.parseInt(betField.getText())*(1.5));
                        messageLabel.setText("You earned "+earnedMoney+"$ money");
                    }else{
                        
                        int resultDice=result+selectedDice;
                       
                        showResult(resultDice);
                        messageLabel.setText("You lost "+betField.getText()+"$ money");
                        
                    }
                    
                }
                }else{
                    messageLabel.setText("Please enter bet amount greater than 1000$");
                }
                
            }
            
        }
        fillMoneyInformation();
        
    }//GEN-LAST:event_rollDiceButtonActionPerformed
    private void showResult(int result){
        if(result==1){
            resultLabel.setVisible(true);
            resultLabel.setIcon(new javax.swing.ImageIcon("redDice.png"));  
        }else if(result==2){
             resultLabel.setVisible(true);
            resultLabel.setIcon(new javax.swing.ImageIcon("redDice2.png"));
        }else if(result==3){
             resultLabel.setVisible(true);
            resultLabel.setIcon(new javax.swing.ImageIcon("redDice3.png"));
        }else{
             resultLabel.setVisible(true);
            resultLabel.setIcon(new javax.swing.ImageIcon("redDice4.png"));
        }
    }
    private void clearBorder(){
        dice1Label.setBorder(null);
        dice2Label.setBorder(null);
        dice3Label.setBorder(null);
        dice4Label.setBorder(null);
    }
    private void dice2LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dice2LabelMouseClicked
         resultLabel.setVisible(false);
        messageLabel.setText("");
        selectedDice=2;
        clearBorder();
        dice2Label.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(51, 255, 0)));
        
        
        
    }//GEN-LAST:event_dice2LabelMouseClicked

    private void dice3LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dice3LabelMouseClicked
        resultLabel.setVisible(false);
        messageLabel.setText("");
        selectedDice=3;
       clearBorder();
       dice3Label.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(51, 255, 0)));
    }//GEN-LAST:event_dice3LabelMouseClicked

    private void dice4LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dice4LabelMouseClicked
        resultLabel.setVisible(false);
        messageLabel.setText("");
        selectedDice=4;
       clearBorder();
       dice4Label.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(51, 255, 0)));
    }//GEN-LAST:event_dice4LabelMouseClicked

    private void dice1LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dice1LabelMouseClicked
       resultLabel.setVisible(false);
        messageLabel.setText("");
       selectedDice=1;
       clearBorder();
       dice1Label.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(51, 255, 0)));
    }//GEN-LAST:event_dice1LabelMouseClicked

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        selectedDice=-1;
        clearBorder();
    }//GEN-LAST:event_formMouseClicked

    private void betFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_betFieldMouseClicked
        betField.setText("");
    }//GEN-LAST:event_betFieldMouseClicked

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        this.setVisible(false);
        CustomerFrame customerFrame=new CustomerFrame(customer.getUserId());
        customerFrame.setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JTextField betField;
    private javax.swing.JLabel dice1Label;
    private javax.swing.JLabel dice2Label;
    private javax.swing.JLabel dice3Label;
    private javax.swing.JLabel dice4Label;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel messageLabel;
    private javax.swing.JLabel moneyLabel;
    private javax.swing.JLabel resultLabel;
    private javax.swing.JButton rollDiceButton;
    // End of variables declaration//GEN-END:variables
}
