/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.operations.ObjectFinder;
import controller.operations.userOperations.CustomerOperations;
import model.product.Product;
import model.product.WoodenBookshelf;
import model.product.WoodenTable;
import model.product.WoodenWardrobe;
import model.users.Customer;

/**
 *
 * @author Ege
 */
public class SellProductFrame extends javax.swing.JFrame {
    Customer customer;
    int customerId;

    /**
     * Creates new form MyProductsFrame
     */
    public SellProductFrame(int customerId) {
        this.customerId=customerId;
        this.customer=ObjectFinder.findCustomerFromCustomerId(this.customerId);
        initComponents();
        fillProductAmountInformation();
        clearAllMessage();
        
        
        
    }
    private void fillProductAmountInformation(){
        initialMoneyInformation();
        
        for(Product p:customer.getProducts()){
            if(p.getProductId()==new WoodenTable().getProductId()){
                numberOfTable.setText(String.valueOf(p.getNumberOfProduct()));   
            }else if(p.getProductId()==new WoodenBookshelf().getProductId()){
                numberOfBookShelf.setText(String.valueOf(p.getNumberOfProduct()));
            }else if(p.getProductId()==new WoodenWardrobe().getProductId()){
                numberOfWardrobe.setText(String.valueOf(p.getNumberOfProduct()));
            }
        }
    }
    private void initialMoneyInformation(){
        numberOfTable.setText("0");
        numberOfWardrobe.setText("0");
        numberOfBookShelf.setText("0");
                
    }
    private void clearAllMessage(){
        messageSellTable.setText("");
        messageSellBookshelf.setText("");
        messageSellWardrobe.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tableIconLabel = new javax.swing.JLabel();
        wardrobeIconLabel = new javax.swing.JLabel();
        numberOfTable = new javax.swing.JLabel();
        numberOfWardrobe = new javax.swing.JLabel();
        bookShelfIconLabel = new javax.swing.JLabel();
        numberOfBookShelf = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        sellTableAmount = new javax.swing.JTextField();
        sellTableAmountLabel = new javax.swing.JLabel();
        sellTableButton = new javax.swing.JButton();
        selWardrobeAmountLable = new javax.swing.JLabel();
        sellWardrobeAmount = new javax.swing.JTextField();
        sellWardrobeButton = new javax.swing.JButton();
        sellBookshelfAmountLable = new javax.swing.JLabel();
        sellBookShelfAmount = new javax.swing.JTextField();
        sellBookShelfButton = new javax.swing.JButton();
        messageSellTable = new javax.swing.JLabel();
        messageSellWardrobe = new javax.swing.JLabel();
        messageSellBookshelf = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tableIconLabel.setIcon(new javax.swing.ImageIcon("table-256.png")); // NOI18N

        wardrobeIconLabel.setIcon(new javax.swing.ImageIcon("wardrobe-256.png")); // NOI18N

        numberOfTable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numberOfTable.setText("67");

        numberOfWardrobe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numberOfWardrobe.setText("43");

        bookShelfIconLabel.setIcon(new javax.swing.ImageIcon("books-256.png")); // NOI18N

        numberOfBookShelf.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numberOfBookShelf.setText("32");

        backButton.setIcon(new javax.swing.ImageIcon("arrow-112-48.png")); // NOI18N
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        sellTableAmount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sellTableAmountMouseClicked(evt);
            }
        });
        sellTableAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sellTableAmountActionPerformed(evt);
            }
        });

        sellTableAmountLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        sellTableAmountLabel.setText("Sell Table Amount:");

        sellTableButton.setBackground(new java.awt.Color(0, 230, 64));
        sellTableButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sellTableButton.setText("Sell Table");
        sellTableButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sellTableButtonActionPerformed(evt);
            }
        });

        selWardrobeAmountLable.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        selWardrobeAmountLable.setText("Sell Wardrobe Amount:");

        sellWardrobeAmount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sellWardrobeAmountMouseClicked(evt);
            }
        });

        sellWardrobeButton.setBackground(new java.awt.Color(0, 230, 64));
        sellWardrobeButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sellWardrobeButton.setText("Sell Wardrobe");
        sellWardrobeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sellWardrobeButtonActionPerformed(evt);
            }
        });

        sellBookshelfAmountLable.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        sellBookshelfAmountLable.setText("Sell Bookshelf Amou�nt:");

        sellBookShelfAmount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sellBookShelfAmountMouseClicked(evt);
            }
        });

        sellBookShelfButton.setBackground(new java.awt.Color(0, 230, 64));
        sellBookShelfButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sellBookShelfButton.setText("Sell Bookshelf");
        sellBookShelfButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sellBookShelfButtonActionPerformed(evt);
            }
        });

        messageSellTable.setText("message");

        messageSellWardrobe.setText("message");

        messageSellBookshelf.setText("message");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(numberOfTable, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(205, 205, 205)
                .addComponent(numberOfWardrobe, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(numberOfBookShelf, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(122, 122, 122))
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sellTableAmountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sellTableAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(113, 113, 113)
                        .addComponent(selWardrobeAmountLable, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sellWardrobeAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(96, 96, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bookShelfIconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(sellBookshelfAmountLable, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(sellBookShelfAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(48, 48, 48))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(messageSellTable, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(tableIconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(105, 105, 105)
                                .addComponent(wardrobeIconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(messageSellWardrobe, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(83, 83, 83)
                                .addComponent(messageSellBookshelf, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(32, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(sellTableButton, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(252, 252, 252)
                .addComponent(sellWardrobeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sellBookShelfButton, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(wardrobeIconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bookShelfIconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numberOfWardrobe, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numberOfBookShelf, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                        .addComponent(tableIconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(numberOfTable, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sellTableAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sellTableAmountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(selWardrobeAmountLable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sellWardrobeAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sellBookshelfAmountLable, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sellBookShelfAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sellTableButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sellWardrobeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sellBookShelfButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(messageSellTable, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(messageSellWardrobe, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(messageSellBookshelf, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        CustomerFrame customeFrame=new CustomerFrame(customer.getUserId());
        this.setVisible(false);
        customeFrame.setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    private void sellTableAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sellTableAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sellTableAmountActionPerformed

    private void sellTableButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sellTableButtonActionPerformed
        if(sellTableAmount.getText().equals("")){
            messageSellTable.setText("Please enter an amount to sell WoodenTable");
        }else{
            int sellAmount=Integer.parseInt(sellTableAmount.getText());
            String message=CustomerOperations.sellWoodenTable(customer, sellAmount);
            messageSellTable.setText(message);
            fillProductAmountInformation();
        }
    }//GEN-LAST:event_sellTableButtonActionPerformed

    private void sellTableAmountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sellTableAmountMouseClicked
        clearAllMessage();
    }//GEN-LAST:event_sellTableAmountMouseClicked

    private void sellWardrobeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sellWardrobeButtonActionPerformed
         if(sellWardrobeAmount.getText().equals("")){
            messageSellWardrobe.setText("Please enter an amount to sell WoodenWardrobe");
        }else{
            int sellAmount=Integer.parseInt(sellWardrobeAmount.getText());
            String message=CustomerOperations.sellWoodenWardrobe(customer, sellAmount);
            messageSellWardrobe.setText(message);
            fillProductAmountInformation();
        }
    }//GEN-LAST:event_sellWardrobeButtonActionPerformed

    private void sellBookShelfButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sellBookShelfButtonActionPerformed
        if(sellBookShelfAmount.getText().equals("")){
            messageSellBookshelf.setText("Please enter an amount to sell WoodenWardrobe");
        }else{
            int sellAmount=Integer.parseInt(sellBookShelfAmount.getText());
            String message=CustomerOperations.sellWoodenBookshelf(customer, sellAmount);
            messageSellBookshelf.setText(message);
            fillProductAmountInformation();
        }
    }//GEN-LAST:event_sellBookShelfButtonActionPerformed

    private void sellWardrobeAmountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sellWardrobeAmountMouseClicked
       clearAllMessage();
    }//GEN-LAST:event_sellWardrobeAmountMouseClicked

    private void sellBookShelfAmountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sellBookShelfAmountMouseClicked
       clearAllMessage();
    }//GEN-LAST:event_sellBookShelfAmountMouseClicked

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel bookShelfIconLabel;
    private javax.swing.JLabel messageSellBookshelf;
    private javax.swing.JLabel messageSellTable;
    private javax.swing.JLabel messageSellWardrobe;
    private javax.swing.JLabel numberOfBookShelf;
    private javax.swing.JLabel numberOfTable;
    private javax.swing.JLabel numberOfWardrobe;
    private javax.swing.JLabel selWardrobeAmountLable;
    private javax.swing.JTextField sellBookShelfAmount;
    private javax.swing.JButton sellBookShelfButton;
    private javax.swing.JLabel sellBookshelfAmountLable;
    private javax.swing.JTextField sellTableAmount;
    private javax.swing.JLabel sellTableAmountLabel;
    private javax.swing.JButton sellTableButton;
    private javax.swing.JTextField sellWardrobeAmount;
    private javax.swing.JButton sellWardrobeButton;
    private javax.swing.JLabel tableIconLabel;
    private javax.swing.JLabel wardrobeIconLabel;
    // End of variables declaration//GEN-END:variables
}
