/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.Data;
import controller.operations.ObjectFinder;
import controller.operations.userOperations.CustomerOperations;
import javax.swing.table.DefaultTableModel;
import model.RequestStatus;
import model.RequestType;
import model.customerFamily.GrandParent;
import model.customerFamily.Parent;
import model.customerFamily.Sibling;
import model.users.Customer;

/**
 *
 * @author Ege
 */
public class WishMoneyFromFamilyFrame extends javax.swing.JFrame {
    Customer customer;
    int customerId;

    /**
     * Creates new form WishMoneyFromFamilyFrame
     */
    public WishMoneyFromFamilyFrame(int customerId) {
        this.customer=ObjectFinder.findCustomerFromCustomerId(customerId);
        initComponents();
        fillCurrentMoneyOfFamilyInformation(customer.getUserId());
        fillPreviousWishesTable();
        messageWishMoney.setText("");
    }
    void fillCurrentMoneyOfFamilyInformation(int customerId){
        this.customer=ObjectFinder.findCustomerFromCustomerId(customerId);
        String dolarSembol="$";
        siblingMoneyLabel.setText("");
        parentsMoneyLabel.setText("");
        grandParentsMoneyLabel.setText("");
        Sibling sibling=ObjectFinder.getSiblingFromId(customer.getUserId());
        Parent parent=ObjectFinder.findParentFromFamilyId(customer.getUserId());
        GrandParent grandParent=ObjectFinder.findGrandParentFromFamilyId(customer.getUserId());
        siblingMoneyLabel.setText(String.valueOf((int)sibling.getMoney()).concat(dolarSembol));
        parentsMoneyLabel.setText(String.valueOf((int)parent.getMoney()).concat(dolarSembol));
        grandParentsMoneyLabel.setText(String.valueOf((int)grandParent.getMoney()).concat(dolarSembol));
    }
    void fillPreviousWishesTable(){
         DefaultTableModel model=(DefaultTableModel) previousWishesTable.getModel();
       for(int i=0;i<customer.getRequests().size();i++){
           if(customer.getRequests().get(i).getRequestType().equals(RequestType.WishMoneyFromFamily)){
               Object[] wishes={String.valueOf(customer.getRequests().get(i).getAmount()),String.valueOf(customer.getRequests().get(i).getRequestType())
         ,String.valueOf(customer.getRequests().get(i).getStatus())}; 
         model.addRow(wishes);
           }
          
         
       }
    }
    
    private void removeRows(){
        DefaultTableModel model=(DefaultTableModel) previousWishesTable.getModel();
        int row=0;
        while(model.getRowCount()>0){
            model.removeRow(row);
        } 
    }
    
     
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        previousWishesTable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        siblingMoneyLabel = new javax.swing.JLabel();
        parentsMoneyLabel = new javax.swing.JLabel();
        grandParentsMoneyLabel = new javax.swing.JLabel();
        moneyAmountToWishField = new javax.swing.JTextField();
        wishMoneyButton = new javax.swing.JButton();
        messageWishMoney = new javax.swing.JLabel();
        backToCustomerFrameButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        previousWishesTable.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        previousWishesTable.setForeground(new java.awt.Color(51, 51, 51));
        previousWishesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Wish Amount", "Request Type", "Request Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(previousWishesTable);
        if (previousWishesTable.getColumnModel().getColumnCount() > 0) {
            previousWishesTable.getColumnModel().getColumn(0).setResizable(false);
            previousWishesTable.getColumnModel().getColumn(1).setResizable(false);
            previousWishesTable.getColumnModel().getColumn(2).setResizable(false);
        }

        jPanel1.setBackground(new java.awt.Color(250, 190, 88));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Previous Wishes");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(135, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(29, 29, 29))
        );

        jPanel2.setBackground(new java.awt.Color(0, 230, 64));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon("banknotes-24.png")); // NOI18N
        jLabel2.setText("Current Money of Family Members");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel2)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(0, 230, 64));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setText("Sibling:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setText("Parents:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setText("Grandparents:");

        siblingMoneyLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        siblingMoneyLabel.setText("234");

        parentsMoneyLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        parentsMoneyLabel.setText("456");

        grandParentsMoneyLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        grandParentsMoneyLabel.setText("678");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE))
                    .addComponent(jLabel5))
                .addGap(36, 36, 36)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(siblingMoneyLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                    .addComponent(parentsMoneyLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(grandParentsMoneyLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(siblingMoneyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(parentsMoneyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(grandParentsMoneyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(74, Short.MAX_VALUE))
        );

        moneyAmountToWishField.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        moneyAmountToWishField.setText("Money Amount:");
        moneyAmountToWishField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                moneyAmountToWishFieldMouseClicked(evt);
            }
        });

        wishMoneyButton.setIcon(new javax.swing.ImageIcon("pray (1).png")); // NOI18N
        wishMoneyButton.setText("Wish Money");
        wishMoneyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wishMoneyButtonActionPerformed(evt);
            }
        });

        messageWishMoney.setText("messageArea");

        backToCustomerFrameButton.setIcon(new javax.swing.ImageIcon("arrow-112-48.png")); // NOI18N
        backToCustomerFrameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToCustomerFrameButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(wishMoneyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(moneyAmountToWishField, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(backToCustomerFrameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(messageWishMoney, javax.swing.GroupLayout.PREFERRED_SIZE, 775, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backToCustomerFrameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addComponent(moneyAmountToWishField, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(wishMoneyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(messageWishMoney, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void moneyAmountToWishFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moneyAmountToWishFieldMouseClicked
        moneyAmountToWishField.setText("");
        messageWishMoney.setText("");
               
    }//GEN-LAST:event_moneyAmountToWishFieldMouseClicked

    private void wishMoneyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wishMoneyButtonActionPerformed
       int wishMoney=Integer.parseInt(moneyAmountToWishField.getText());
       String message=CustomerOperations.requestMoney(customer, wishMoney);
       //this.customer=ObjectFinder.findCustomerFromCustomerId(customer.getUserId());
       messageWishMoney.setText(String.valueOf(message));
       
       removeRows();
       fillCurrentMoneyOfFamilyInformation(customer.getUserId());
       fillPreviousWishesTable();
       
    }//GEN-LAST:event_wishMoneyButtonActionPerformed

    private void backToCustomerFrameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToCustomerFrameButtonActionPerformed
        //Customer customerr=ObjectFinder.findCustomerFromCustomerId(customer.getUserId());
        //this.customer=customerr;
        CustomerFrame customerFrame=new CustomerFrame(customer.getUserId());
        this.setVisible(false);
        customerFrame.setVisible(true);
    }//GEN-LAST:event_backToCustomerFrameButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backToCustomerFrameButton;
    private javax.swing.JLabel grandParentsMoneyLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel messageWishMoney;
    private javax.swing.JTextField moneyAmountToWishField;
    private javax.swing.JLabel parentsMoneyLabel;
    private javax.swing.JTable previousWishesTable;
    private javax.swing.JLabel siblingMoneyLabel;
    private javax.swing.JButton wishMoneyButton;
    // End of variables declaration//GEN-END:variables
}
